add load comments feature
htmlacademy-javascript/1066359-kekstagram-24 pull request #8
Opened 2021-11-08 15:20 UTC by dassshha

В разметке описано
 `<div class="social__comment-count">5 из <span class="comments-count">125</span> комментариев</div>`
Счетчик меняется при нажатии кнопки загрузить, единственное что, если изначально комментариев меньше 5, то пишется `5 из 3 комментариев`.В задании не было поэтому поводу ничего написано, поэтому я это пока не изменяла.

2021-11-08 17:52 UTC, slyvkanychmykyta requested changes

2021-11-08 17:52 UTC, slyvkanychmykyta commented on js/big-picture.js
> +const commentsList = bigPicture.querySelector('.social__comments');
`const commentsContainer = bigPicture.querySelector('.social__comments');`
`const comments = commentsList.children;`

2021-11-08 17:52 UTC, slyvkanychmykyta commented on js/big-picture.js
> +let loadedCommentsCount = COMMENTS_AT_ONCE_LOAD_COUNT;
константу нужно вынести в файлик с константами

2021-11-08 17:52 UTC, slyvkanychmykyta commented on js/big-picture.js
> +const onLoadNewCommentsButtonClicked = () => {
`onLoadNewCommentsButtonClick`

2021-11-08 17:52 UTC, slyvkanychmykyta commented on js/big-picture.js
> +import {COMMENTS_AT_ONCE_LOAD_COUNT} from './constants.js';
Если открыть большое изображение и нажать загрузить еще комметарии, то при открытии другого изображения счетчик комментариев останется с предыдущего изображения, нужно это поправить

2021-11-11 11:48 UTC, dassshha commented on js/big-picture.js
> +let loadedCommentsCount = COMMENTS_AT_ONCE_LOAD_COUNT;
она и так в отдельном файле, а это переменянная, начальное значение которой равно константе, но значение переменной будет меняться

2021-11-11 11:52 UTC, slyvkanychmykyta commented on js/big-picture.js
> +let loadedCommentsCount = COMMENTS_AT_ONCE_LOAD_COUNT;
тогда все ок, ошибся

2021-11-11 12:07 UTC, slyvkanychmykyta approved these changes

2021-11-11 12:07 UTC, merged