Add scale and effects with slider
htmlacademy-javascript/1066359-kekstagram-24 pull request #9
Opened 2021-11-12 21:06 UTC by dassshha

2021-11-12 22:08 UTC, slyvkanychmykyta requested changes

2021-11-12 22:08 UTC, slyvkanychmykyta commented on js/slider.js
> +slider.classList.add('hidden');
эту строку можно перенести вверх и сделать похожую функцию инициализации слайдера, тут будет две инструкции 
```
slider.classList.add('hidden');
valueField.value = 30;
```

2021-11-12 22:08 UTC, slyvkanychmykyta commented on js/slider.js
> +valueField.value = 30;
30 лучше вынести в константу

2021-11-12 22:08 UTC, slyvkanychmykyta commented on js/slider.js
> +  if (effect === '-chrome') {
названия эффектов лучше вынести в объект

2021-11-12 22:08 UTC, slyvkanychmykyta commented on js/slider.js
> +  changeEffect(0, 1, 0.1, formatToFloat, formatFromFloat);
все значения эффектов нужно вынести в объекты, можно отдельно под каждый эффект

2021-11-13 18:31 UTC, dassshha commented on js/slider.js
> +slider.classList.add('hidden');
я эту строку лучше оставлю, как есть, а `valueField.value = 30;` удалю, она по факту не нужна

2021-11-14 16:47 UTC, slyvkanychmykyta approved these changes

2021-11-14 16:47 UTC, merged